In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors as neighbors
import random
import pickle
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
path = "drive/My Drive/Colab Notebooks/data/Datasets_Healthy_Older_People/S1_Dataset"
files = os.listdir(path)
gender_list = []
for i in range(len(files)):
    gender_list.append(files[i][-1])
dataset = []
for i in range(len(files)):
    lines = []
    file_path = path + "/" + files[i]
    file = open(file_path, "r")
    while True:
        every_line = file.readline()
        if not every_line:
            break
        every_line = every_line.strip().split(",")
        every_line.insert(-1, (1. if gender_list[i] is "M" else 0.))
        lines = [float(x) for x in every_line]
        dataset.append(lines)
random.shuffle(dataset)
values = []
classes = []
for i in range(len(dataset)):
    values.append(dataset[i][0:-1])
    classes.append(int(dataset[i][-1])-1)
print(classes.count(0)/classes.count(3))
print(classes.count(1)/classes.count(3))
print(classes.count(2)/classes.count(3))
print(classes.count(3)/classes.count(3))
print(classes.count(0)/len(classes))
print(classes.count(1)/len(classes))
print(classes.count(2)/len(classes))
print(classes.count(3)/len(classes))
values = np.array(values)
classes = np.array(classes)

7.161065037101702
2.1436054124836317
22.487996508075078
1.0
0.21837397508252582
0.06536843786604196
0.6857629645405176
0.030494622510914705


In [ ]:
train_split = 0.7

train_value_set = values[0:int(train_split*len(values))]
train_class_set = classes[0:int(train_split*len(classes))]
test_value_set = values[int(train_split*len(values)):]
test_class_set = classes[int(train_split*len(classes)):]

In [ ]:
def select(condition, prediction, classes):
  count = 0
  length = 0
  for pre, classe in zip(prediction, classes):
    if pre == classe and pre == condition:
      count += 1
      length += 1
    elif classe == condition:
      length += 1
  # print(count)
  print(confusion_matrix(classes, prediction))
  print(classification_report(classes, prediction))
  return count, length

In [ ]:
model = neighbors.KNeighborsClassifier(n_neighbors=1,weights="uniform")
model.fit(train_value_set, np.expand_dims(train_class_set, 1))
prediction = model.predict(test_value_set)
count, length = select(3, prediction, test_class_set)
print(count / length)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


0.6955903271692745


In [ ]:
with open("/content/drive/My Drive/Colab Notebooks/data/Models/KNN/KNN.pickle", "wb") as f:
    pickle.dump(model, f)

NameError: ignored

In [ ]:
list_para = [i + 1 for i in range(50)]
print(list_para)
for i in range(len(list_para)):
  model = neighbors.KNeighborsClassifier(n_neighbors=list_para[i],weights="distance")
  model.fit(train_value_set, np.expand_dims(train_class_set, 1))
  prediction = model.predict(test_value_set)
  pre_arr = np.array(prediction)
  print(np.sum(pre_arr == test_class_set) / len(test_class_set))
  count, length = select(3, prediction, test_class_set)
  print(count)
  print(length)
  print(count / length)

In [ ]:
model = pickle.load(open("/content/drive/My Drive/Colab Notebooks/data/Models/KNN/KNN.pickle", "rb"))
prediction = model.predict(test_value_set)
pre_arr = np.array(prediction)
print(np.sum(pre_arr == test_class_set) / len(test_class_set))
count, length = select(0, prediction, test_class_set)
print(count)
print(length)
print(count / length)

0.9772838191579041
[[ 4645    50   154    15]
 [   47  1385    24     4]
 [  108    28 15372    13]
 [   23     6    40   625]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.96      4864
           1       0.94      0.95      0.95      1460
           2       0.99      0.99      0.99     15521
           3       0.95      0.90      0.93       694

    accuracy                           0.98     22539
   macro avg       0.96      0.95      0.95     22539
weighted avg       0.98      0.98      0.98     22539

4645
4864
0.9549753289473685
